apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    {{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
    {{- end }}
type: Opaque
data:
  # Waiting for https://github.com/kubernetes/helm/issues/1754
  google-service-account.json: {{ .Values.googleServiceAccount }}
